security:
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db_provider]
        in_memory:
            memory:
                users:
                    superadmin:
                        password: 'superadminpw'
                        roles: ['ROLE_SUPER_ADMIN']
        user_db_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/token
            stateless: true
            anonymous: true
            json_login:
                provider: chain_provider
                check_path: /api/token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: chain_provider
        api_register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            anonymous: false
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true
            logout:
                path: app_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\FacebookAuthenticator
                    - App\Security\GoogleAuthenticator
                    - App\Security\TokenAuthenticator
                entry_point: App\Security\LoginFormAuthenticator
            provider: user_db_provider
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/editor, roles: ROLE_EDITOR }
        # - { path: ^/contributor, roles: ROLE_CONTRIBUTOR }
        # - { path: ^/profile, roles: ROLE_USER }
