twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '_form/float.html.twig'
    globals:
        header: '@App\Service\HeaderService'
        default_avatar: '/images/avatar.png'
        default_picture: '/images/picture.png'