# Virtual Hosts
#
<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot "c:/wamp/www"
  <Directory "c:/wamp/www/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    #Require all granted
		Allow from all
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName haja.emediaplace.com
  ServerAlias haja.emediaplace.com
  DocumentRoot "c:/wamp/www/web"
  ErrorLog "logs/error.log"
  CustomLog "logs/access.log" common
  <Directory "c:/wamp/www/web/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride all
		Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName software.emediaplace.com
  ServerAlias software.emediaplace.com
  DocumentRoot "c:/wamp/www/lasentinelle/software"
  ErrorLog "logs/error.log"
  CustomLog "logs/access.log" common
  <Directory "c:/wamp/www/lasentinelle/software/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride all
		Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName kiosque.lasentinelle.com
  ServerAlias kiosque.lasentinelle.com
  DocumentRoot "c:/wamp/www/lasentinelle/web"
  ErrorLog "logs/error.log"
  CustomLog "logs/access.log" common
  <Directory "c:/wamp/www/lasentinelle/web/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName manjaka.emediaplace.com
  ServerAlias manjaka.emediaplace.com
  DocumentRoot "c:/wamp/projetAvril/public"
  ErrorLog "logs/error.log"
  CustomLog "logs/access.log" common
  <Directory "c:/wamp/projetAvril/public/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName extplorer.loc
  ServerAlias extplorer.loc
  DocumentRoot "c:/wamp/www/eXtplorer"
  ErrorLog "logs/error.log"
  CustomLog "logs/access.log" common
  <Directory "c:/wamp/www/eXtplorer/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName saas-project.com
  ServerAlias saas-project.com
  DocumentRoot "C:/wamp/www/other/project/public"
  ErrorLog "logs/error.log"
  CustomLog "logs/access.log" common
  <Directory "C:/wamp/www/other/project/public/">
    DirectoryIndex index.php
	Options Indexes Includes FollowSymLinks MultiViews
	AllowOverride All
	Require all granted
  </Directory>
</VirtualHost>
