rest_controller:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/{version}
web_controller:
    resource: ../../src/Controller/Web/
    type: annotation
    prefix:
        fr: '' # don't prefix URLs for French, the default locale
        en: '/en'
