<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200207090522 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE access_log ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL, CHANGE ip ip VARCHAR(100) DEFAULT NULL, CHANGE user_agent user_agent VARCHAR(255) DEFAULT NULL, CHANGE referer referer VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE activities CHANGE address_id address_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE budget budget DOUBLE PRECISION DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE contact_email contact_email VARCHAR(255) DEFAULT NULL, CHANGE contact_phone contact_phone VARCHAR(255) DEFAULT NULL, CHANGE contact_address contact_address VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE activity_contributions CHANGE user_id user_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE roles roles JSON NOT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE activities_favorites CHANGE user_id user_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE activities_favorites RENAME INDEX idx_c8cf3ed7a76ed395 TO IDX_2AF3E33A76ED395');
        $this->addSql('ALTER TABLE activities_favorites RENAME INDEX idx_c8cf3ed781c06096 TO IDX_2AF3E3381C06096');
        $this->addSql('ALTER TABLE activities_files CHANGE file_id file_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE addresses CHANGE address_line1 address_line1 VARCHAR(255) DEFAULT NULL, CHANGE address_line2 address_line2 VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(255) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE axes CHANGE graph_id graph_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE start_at start_at DATETIME DEFAULT NULL, CHANGE end_at end_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE downloads CHANGE user_id user_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE ip ip VARCHAR(100) DEFAULT NULL, CHANGE type type VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE files CHANGE author_id author_id INT DEFAULT NULL, CHANGE path path VARCHAR(255) DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL, CHANGE mime_type mime_type VARCHAR(255) DEFAULT NULL, CHANGE size size INT DEFAULT NULL, CHANGE display_name display_name VARCHAR(255) DEFAULT NULL, CHANGE is_instantly is_instantly TINYINT(1) DEFAULT NULL, CHANGE type type VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE files_tags CHANGE file_id file_id INT DEFAULT NULL, CHANGE tag_id tag_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE goals CHANGE author_id author_id INT DEFAULT NULL, CHANGE indicator_id indicator_id INT DEFAULT NULL, CHANGE iteration_id iteration_id INT DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE graphes CHANGE project_id project_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE indicators CHANGE author_id author_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE unit_id unit_id INT DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE indicators_favorites CHANGE user_id user_id INT DEFAULT NULL, CHANGE indicator_id indicator_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE indicators_favorites RENAME INDEX idx_627d80aa76ed395 TO IDX_D6ED007A76ED395');
        $this->addSql('ALTER TABLE indicators_favorites RENAME INDEX idx_627d80a4402854a TO IDX_D6ED0074402854A');
        $this->addSql('ALTER TABLE iterations CHANGE author_id author_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE start_at start_at DATETIME DEFAULT NULL, CHANGE end_at end_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE metas CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE object_id object_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE options CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE periodicities CHANGE author_id author_id INT DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE projects CHANGE address_id address_id INT DEFAULT NULL, CHANGE periodicity_id periodicity_id INT DEFAULT NULL, CHANGE budget budget DOUBLE PRECISION DEFAULT NULL, CHANGE start_at start_at DATETIME DEFAULT NULL, CHANGE end_at end_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE contact_email contact_email VARCHAR(255) DEFAULT NULL, CHANGE contact_phone contact_phone VARCHAR(255) DEFAULT NULL, CHANGE contact_address contact_address VARCHAR(255) DEFAULT NULL, CHANGE currency currency VARCHAR(100) DEFAULT NULL, CHANGE slug slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE project_contributions CHANGE user_id user_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE roles roles JSON NOT NULL, CHANGE status status VARCHAR(10) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE reports CHANGE author_id author_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE synced_at synced_at DATETIME DEFAULT NULL, CHANGE status status VARCHAR(10) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE longitude longitude VARCHAR(255) DEFAULT NULL, CHANGE latitude latitude VARCHAR(255) DEFAULT NULL, CHANGE altitude altitude VARCHAR(255) DEFAULT NULL, CHANGE location_title location_title VARCHAR(255) DEFAULT NULL, CHANGE publish_externally publish_externally TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE reports_files CHANGE file_id file_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE report_id report_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE results CHANGE author_id author_id INT DEFAULT NULL, CHANGE report_id report_id INT DEFAULT NULL, CHANGE indicator_id indicator_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE longitude longitude VARCHAR(255) DEFAULT NULL, CHANGE latitude latitude VARCHAR(255) DEFAULT NULL, CHANGE altitude altitude VARCHAR(255) DEFAULT NULL, CHANGE location_title location_title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tags CHANGE project_id project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE units CHANGE author_id author_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE main main TINYINT(1) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE users CHANGE address_id address_id INT DEFAULT NULL, CHANGE facebook_id facebook_id VARCHAR(255) DEFAULT NULL, CHANGE google_id google_id VARCHAR(255) DEFAULT NULL, CHANGE roles roles JSON NOT NULL, CHANGE language language VARCHAR(2) DEFAULT NULL, CHANGE full_name full_name VARCHAR(100) DEFAULT NULL, CHANGE title title VARCHAR(100) DEFAULT NULL, CHANGE presentation presentation VARCHAR(255) DEFAULT NULL, CHANGE company company VARCHAR(100) DEFAULT NULL, CHANGE phone phone VARCHAR(50) DEFAULT NULL, CHANGE website website VARCHAR(50) DEFAULT NULL, CHANGE status status VARCHAR(10) DEFAULT NULL, CHANGE confirm_token confirm_token VARCHAR(255) DEFAULT NULL, CHANGE confirmed_at confirmed_at DATETIME DEFAULT NULL, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL, CHANGE reseted_at reseted_at DATETIME DEFAULT NULL, CHANGE actived_at actived_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE last_activity_at last_activity_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE ext_log_entries CHANGE object_id object_id VARCHAR(64) DEFAULT NULL, CHANGE data data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', CHANGE username username VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE access_log DROP created_at, DROP updated_at, CHANGE user_id user_id INT DEFAULT NULL, CHANGE url url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ip ip VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE user_agent user_agent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE referer referer VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE activities CHANGE address_id address_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE budget budget DOUBLE PRECISION DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE contact_email contact_email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact_phone contact_phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact_address contact_address VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE activities_favorites CHANGE user_id user_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE activities_favorites RENAME INDEX idx_2af3e33a76ed395 TO IDX_C8CF3ED7A76ED395');
        $this->addSql('ALTER TABLE activities_favorites RENAME INDEX idx_2af3e3381c06096 TO IDX_C8CF3ED781C06096');
        $this->addSql('ALTER TABLE activities_files CHANGE file_id file_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE activity_contributions CHANGE user_id user_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE addresses CHANGE address_line1 address_line1 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE address_line2 address_line2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE state state VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postal_code postal_code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE axes CHANGE graph_id graph_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE start_at start_at DATETIME DEFAULT \'NULL\', CHANGE end_at end_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE downloads CHANGE user_id user_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE ip ip VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE type type VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ext_log_entries CHANGE object_id object_id VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE data data LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\', CHANGE username username VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE files CHANGE author_id author_id INT DEFAULT NULL, CHANGE path path VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE url url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mime_type mime_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE size size INT DEFAULT NULL, CHANGE display_name display_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_instantly is_instantly TINYINT(1) DEFAULT \'NULL\', CHANGE type type VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE files_tags CHANGE file_id file_id INT DEFAULT NULL, CHANGE tag_id tag_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE goals CHANGE author_id author_id INT DEFAULT NULL, CHANGE indicator_id indicator_id INT DEFAULT NULL, CHANGE iteration_id iteration_id INT DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE graphes CHANGE project_id project_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE indicators CHANGE author_id author_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE unit_id unit_id INT DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE indicators_favorites CHANGE user_id user_id INT DEFAULT NULL, CHANGE indicator_id indicator_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE indicators_favorites RENAME INDEX idx_d6ed007a76ed395 TO IDX_627D80AA76ED395');
        $this->addSql('ALTER TABLE indicators_favorites RENAME INDEX idx_d6ed0074402854a TO IDX_627D80A4402854A');
        $this->addSql('ALTER TABLE iterations CHANGE author_id author_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE start_at start_at DATETIME DEFAULT \'NULL\', CHANGE end_at end_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE metas CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE object_id object_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE options CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE periodicities CHANGE author_id author_id INT DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE project_contributions CHANGE user_id user_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE status status VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE projects CHANGE address_id address_id INT DEFAULT NULL, CHANGE periodicity_id periodicity_id INT DEFAULT NULL, CHANGE budget budget DOUBLE PRECISION DEFAULT \'NULL\', CHANGE start_at start_at DATETIME DEFAULT \'NULL\', CHANGE end_at end_at DATETIME DEFAULT \'NULL\', CHANGE currency currency VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE slug slug VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE contact_email contact_email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact_phone contact_phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact_address contact_address VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE reports CHANGE author_id author_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE synced_at synced_at DATETIME DEFAULT \'NULL\', CHANGE status status VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE publish_externally publish_externally TINYINT(1) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE longitude longitude VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE latitude latitude VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE altitude altitude VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE location_title location_title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE reports_files CHANGE file_id file_id INT DEFAULT NULL, CHANGE activity_id activity_id INT DEFAULT NULL, CHANGE report_id report_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE results CHANGE author_id author_id INT DEFAULT NULL, CHANGE report_id report_id INT DEFAULT NULL, CHANGE indicator_id indicator_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE longitude longitude VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE latitude latitude VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE altitude altitude VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE location_title location_title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE tags CHANGE project_id project_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE units CHANGE author_id author_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE main main TINYINT(1) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE users CHANGE address_id address_id INT DEFAULT NULL, CHANGE facebook_id facebook_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE google_id google_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE language language VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE full_name full_name VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE title title VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE presentation presentation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE company company VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone phone VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE website website VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE status status VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE confirm_token confirm_token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE confirmed_at confirmed_at DATETIME DEFAULT \'NULL\', CHANGE reset_token reset_token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE reseted_at reseted_at DATETIME DEFAULT \'NULL\', CHANGE actived_at actived_at DATETIME DEFAULT \'NULL\', CHANGE last_activity_at last_activity_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
    }
}
